#!/usr/bin/env bash
# post-commit sync — call this AFTER any commit lands on the local main branch.
#
# Ported 2026-09-02 from siamese-reconcile scripts/post_commit_sync.sh and
# adapted to crypto-bot (governance port, S1.3).
#
# What it does, in order:
#   1. Decide whether the last commit touched a repomix-include path. If yes,
#      regenerate repomix-output.xml and create a chore commit. The include
#      spec is repomix.config.json — the ONE list; this script reads it rather
#      than carrying a second copy that could drift.
#   2. git push origin main — ONLY on a manual run with NO flag. The PostToolUse
#      hook (.claude/hooks/post-commit-sync.py) calls this script with
#      --no-push, so routine and intermediate CC commits auto-refresh repomix
#      LOCALLY but never push.
#   3. claudesync push, if and only if claudesync is genuinely configured.
#
# THE PUSH BOUNDARY (CLAUDE.md mandate G, revised 2026-09-02). Trial
# intentionality is preserved by the GATE, not by a human typing `git push`:
# CC runs this script with no flag after a stage whose VERIFY block is green
# (pytest green, eval/run_tier1.py green, commit hooks clean, no sacred path
# staged without SACRED_OVERRIDE_FILES). Force-push, branch deletion, pushing
# any branch but main, live deploy and live capital remain Human-only, and
# .claude/hooks/no-deploy.py blocks the first three at the tool layer.
#
# Why a script and not a git post-commit hook: visibility. Whoever runs this
# sees the repomix regeneration and the push explicitly, instead of both
# hiding behind every commit.
#
# Usage:
#   bash scripts/post_commit_sync.sh            # regen + PUSH  (post-VERIFY)
#   bash scripts/post_commit_sync.sh --no-push  # regen + local commit only (hook)
#
# Exit codes:
#   0 - everything succeeded
#   1 - a step failed; stderr explains
set -euo pipefail

cd "$(dirname "$0")/.."

PUSH=1
for arg in "$@"; do
    case "$arg" in
        --no-push) PUSH=0 ;;
    esac
done

REPOMIX_OUT="repomix-output.xml"
REPOMIX_CONFIG="repomix.config.json"

# ---------------------------------------------------------------- paths
LAST_COMMIT_FILES=$(git diff --name-only HEAD~1..HEAD 2>/dev/null \
    || git diff-tree --no-commit-id --name-only -r HEAD)

# ----------------------------------------- curated sync set (claude.ai)
CURATED_SET=(
    "CLAUDE.md"
    "docs/MASTER_PLAN.md"
    "docs/bot_status.md"
    "docs/handoff_template.md"
    "docs/architecture.md"
    "docs/validation_framework.md"
    ".memory/T2_semantic/facts.md"
    "$REPOMIX_OUT"
)

# --------------------------------------------- repomix include patterns
# Read from repomix.config.json — the include spec is the single source of
# truth. A hardcoded second copy here is exactly the drift that made the
# bash hook layer disagree with itself (see .claude/hooks/_archive_bash_2026-09/README.md).
readarray -t REPOMIX_PATTERNS < <(
    python -c "
import json, sys
try:
    cfg = json.load(open('$REPOMIX_CONFIG'))
except Exception:
    sys.exit(0)
for p in cfg.get('include', []):
    # strip the glob tail: 'docs/**' -> 'docs/', 'config.py' -> 'config.py'
    print(p.split('*', 1)[0])
" 2>/dev/null || true
)

touched_curated() {
    local f
    for f in "${CURATED_SET[@]}"; do
        if echo "$LAST_COMMIT_FILES" | grep -Fxq "$f"; then
            return 0
        fi
    done
    return 1
}

touched_repomix() {
    local p
    [ "${#REPOMIX_PATTERNS[@]}" -eq 0 ] && return 1
    while IFS= read -r changed; do
        [ -z "$changed" ] && continue
        for p in "${REPOMIX_PATTERNS[@]}"; do
            [ -z "$p" ] && continue
            case "$changed" in
                "$p"*) return 0 ;;
            esac
        done
    done <<< "$LAST_COMMIT_FILES"
    return 1
}

run_repomix() {
    echo "==> Regenerating $REPOMIX_OUT"
    if command -v repomix >/dev/null 2>&1; then
        repomix --config "$REPOMIX_CONFIG"
    elif command -v npx >/dev/null 2>&1; then
        npx --yes repomix --config "$REPOMIX_CONFIG"
    else
        echo "ERROR: neither 'repomix' nor 'npx' found on PATH." >&2
        echo "Install: npm install -g repomix" >&2
        return 1
    fi
}

# ------------------------------------------------------------- step 1
if touched_repomix; then
    if run_repomix; then
        if ! git diff --quiet -- "$REPOMIX_OUT" 2>/dev/null; then
            echo "==> repomix output changed — creating chore commit"
            git add "$REPOMIX_OUT"
            short_sha=$(git rev-parse --short HEAD)
            git commit -F - <<COMMIT_MSG
chore(repomix): refresh repomix-output.xml after ${short_sha}

Auto-generated by scripts/post_commit_sync.sh because the previous
commit (${short_sha}) touched files matched by repomix.config.json
include patterns.

[mandate-H]
Co-authored-by: Claude <noreply@anthropic.com>
COMMIT_MSG
        else
            echo "==> repomix output unchanged — no commit needed"
        fi
    else
        echo "WARN: repomix step failed; continuing." >&2
    fi
else
    echo "==> no repomix-included files touched; skipping regen"
fi

# ------------------------------------------------------------- step 2
if [ "$PUSH" -eq 1 ]; then
    BRANCH=$(git rev-parse --abbrev-ref HEAD)
    if [ "$BRANCH" != "main" ]; then
        echo "ERROR: refusing to push branch '$BRANCH'." >&2
        echo "       Pushing any branch but main is Human-only (CLAUDE.md 'Human only')." >&2
        exit 1
    fi
    echo "==> git push origin main"
    if ! git push origin main; then
        echo "ERROR: git push failed. Resolve manually (no force-push, no auto-retry)." >&2
        exit 1
    fi
else
    echo "==> --no-push: local sync only; skipping git push (run without --no-push to push)"
fi

# ------------------------------------------------------------- step 3
# Re-evaluate against the LATEST commit (which may now be the repomix chore).
LAST_COMMIT_FILES=$(git diff --name-only HEAD~1..HEAD 2>/dev/null \
    || git diff-tree --no-commit-id --name-only -r HEAD)

if [ "$PUSH" -ne 1 ]; then
    echo "==> --no-push: skipping claudesync push"
elif ! touched_curated; then
    echo "==> no curated-set files touched; skipping claudesync push"
elif ! command -v claudesync >/dev/null 2>&1 || [ ! -f .claudesync/config.local.json ]; then
    # crypto-bot does not use claudesync today — Kanin refreshes claude.ai
    # project knowledge by hand. Say so plainly instead of emitting a WARN that
    # looks like a failure on every single push.
    echo "==> claudesync not configured, skipped (project knowledge is synced manually)"
else
    echo "==> claudesync push (curated set changed)"
    if ! claudesync push; then
        echo "WARN: claudesync push failed. Likely auth expired — run:" >&2
        echo "  claudesync auth login" >&2
        echo "  claudesync project set" >&2
        exit 1
    fi
fi

echo "==> done"
